package com.accenture.aris.sample.business.repository;

import com.accenture.aris.sample.business.entity.UserEntity;
import com.accenture.aris.sample.business.entity.UserListEntity;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.ResultHandler;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface UserRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int insertSelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    UserEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Jul 10 12:34:28 JST 2014
     */
    List<UserEntity> selectByEntity(UserEntity entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Jul 10 12:34:28 JST 2014
     */
    int countByEntity(UserEntity entity);

    UserEntity selectByNameAndPassword(@Param("name") String name, @Param("password") String password);

    UserEntity selectByName(@Param("name") String name);

    List<UserListEntity> selectByEntityWithCode(UserListEntity record);

    List<UserListEntity> selectByEntityWithCode(UserListEntity record,RowBounds rowBounds);

    UserListEntity selectByPrimaryKeyWithCode(String id);

    List<String> selectByPrimaryKeyAmbiguous(String id);

    int updateByPrimaryKeySelectiveOnForm(UserEntity record);

    void selectByEntityWithHandler(UserEntity record, ResultHandler handler);

    int countByEntityWithCode(UserEntity entity);
    
    String getPassword(String userID);
    
    int changePassword(String password, String userID);
}